### ISSUE TITLE
bug 提交

### ISSUE THREAD

**Issue by kyohan789** [52ludama/linode_panel#1]
root@localhost:~/linode_panel# python3 main.py
Traceback (most recent call last):
  File "/root/linode_panel/main.py", line 5, in <module>
    from flask import Flask, render_template, redirect, url_for, request
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/lib/python3/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/lib/python3/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/dist-packages/markupsafe/__init__.py)

**Comment by 52ludama** [comment]
python -m pip install markupsafe==2.0.1
@kyohan789

**Comment by cse0001** [comment]
The root cause with your issue stems from a dependency management conflict between two software ecosystems. According to the error message, your markupsafe was installed using pip at the path `/usr/local/lib/python3.9/dist-packages/markupsafe/`. The jinja2 that depends on it was installed using apt at the path `/usr/lib/python3/dist-packages/jinja2`. The versions of the two are not compatible. In fact, there is a version of markupsafe in the system that jinja2 correctly depends on, but the Python interpreter prioritizes the markupsafe installed by pip, leading to this issue. There are typically two solutions to this problem: (1) Use pip to uninstall markupsafe, and then reinstall it using apt, or uninstall jinja2 using apt and reinstall it using pip. (2) Use Python's imp module to customize the path and import the markupsafe from the apt path before importing jinja2. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('markupsafe', path)
    imp.load_module("markupsafe", fp, pathname, description)

Hope my diagnosis is helpful to you！@kyohan789

**Comment by owo10086** [comment]
```root@ubuntu:~/linode_panel# python3 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from flask import Flask, render_template, redirect, url_for, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 676, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)
```
一样的问题 

按照作者说的运行 后
sudo ln -s /usr/bin/python3 /usr/bin/python
python -m pip install markupsafe==2.0.1
提示：
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from flask import Flask, render_template, redirect, url_for, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/__init__.py)
```
